import './globals.css'
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Theme, ThemePanel } from '@radix-ui/themes';
import NavBar from './NavBar'
import Provider from './auth/Provider';
import Queryclientprovider from './Queryclientprovider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Issues',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Queryclientprovider>

        <Provider>
          <Theme appearance="light" accentColor="purple" grayColor="gray" radius="large" scaling="105%">  
                    <NavBar/>
                  <main className='p-5'>
                    {children}
                  </main>
                  {/* <ThemePanel/> */}
              </Theme>
        </Provider>
        </Queryclientprovider>
        </body>
    </html>
  )
}
